/* eslint-disable node/prefer-global/process */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import type { createUnimport } from 'unimport'
import type { LoaderContext } from 'webpack'

import { logger } from './logger'

import type { LoaderOptions } from './types'

// module-level caches to avoid repeating work across files
const emittedDts = new Set<string>()

export async function generateAndEmitDts(
  unimport: ReturnType<typeof createUnimport>,
  options: LoaderOptions,
  loaderContext: LoaderContext<LoaderOptions>,
) {
  if (!options.dts) {
    return
  }

  const filename = options.dts === true ? 'auto-imports.d.ts' : String(options.dts)
  if (emittedDts.has(filename)) {
    return
  }

  const dts = await unimport.generateTypeDeclarations()
  const content = `${[
    '/* eslint-disable */',
    '/* prettier-ignore */',
    '// @ts-nocheck',
    '// noinspection JSUnusedGlobalSymbols',
    '// Generated by unplugin-auto-import',
    '// biome-ignore lint: disable',
    dts,
  ].join('\n')}\n`

  // emitFile is available on loader context in many webpack versions
  if ('emitFile' in loaderContext && typeof loaderContext.emitFile === 'function') {
    loaderContext.emitFile(filename, content)
    logger.info(`Emitted type declarations to ${filename}`)
  } else {
    // fallback: write to process.cwd() for Turbopack compatibility
    const filePath = join(process.cwd(), filename)
    try {
      writeFileSync(filePath, content, 'utf-8')
      logger.info(`Wrote type declarations to ${filePath}`)
    } catch (error) {
      logger.error(`Failed to write ${filePath}:`, error)
    }
  }
  emittedDts.add(filename)
}
